# Main Menu

[[main]]
  name = "ì„¸ë¯¸ë‚˜"
  url = "/seminar/"
  weight = 70

[[main]]
  name = "ê³µì§€ì‚¬í•­"
  weight = 30
  identifier = "notice"
  url = "/notice/"

[[main]]
  name = "ì°¸ì—¬ìë“¤"
  weight = 100
  identifier = "people"
  url = "/people/"

[[main]]
  name = "ë°œí‘œìë“¤"
  weight = 150
  identifier = "speakers"
  url = "/speakers/"
  parent = "people"

[[main]]
  name = "ê¸°ì—¬ìë“¤"
  weight = 150
  identifier = "contributors"
  url = "/contributors/"
  parent= "people"

[[main]]
  name = "#íƒœê·¸"
  weight = 200
  identifier = "tags"
  url = "/tags/"

[[main]]
  name = "ğŸ²ëœë¤"
  weight = 300
  url = "#random"

# [[social]]
#   name = "íŠ¸ìœ„í„°ì— ê³µìœ "
#   weight = 250
#   pre = "<svg version=\"1.1\" id=\"twittershare\" class=\"{{ with .class }}{{ . }} {{ end }}icon icon-twitter\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 248 204\" style=\"enable-background:new 0 0 248 204;\" xml:space=\"preserve\" width=\"20\" height=\"20\"><style type=\"text/css\">.st0{fill:#1D9BF0;}</style><g id=\"Logo_1_\"><path id=\"white_background\" class=\"st0\" d=\"M221.95,51.29c0.15,2.17,0.15,4.34,0.15,6.53c0,66.73-50.8,143.69-143.69,143.69v-0.04   C50.97,201.51,24.1,193.65,1,178.83c3.99,0.48,8,0.72,12.02,0.73c22.74,0.02,44.83-7.61,62.72-21.66   c-21.61-0.41-40.56-14.5-47.18-35.07c7.57,1.46,15.37,1.16,22.8-0.87C27.8,117.2,10.85,96.5,10.85,72.46c0-0.22,0-0.43,0-0.64   c7.02,3.91,14.88,6.08,22.92,6.32C11.58,63.31,4.74,33.79,18.14,10.71c25.64,31.55,63.47,50.73,104.08,52.76   c-4.07-17.54,1.49-35.92,14.61-48.25c20.34-19.12,52.33-18.14,71.45,2.19c11.31-2.23,22.15-6.38,32.07-12.26   c-3.77,11.69-11.66,21.62-22.2,27.93c10.01-1.18,19.79-3.86,29-7.95C240.37,35.29,231.83,44.14,221.95,51.29z\"/></g></svg>"
#   url = "#twitter"
#   id = "twitter"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/SNU-SCSC/22F-MLDL-Intermediate"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
